- go.mod
> Switch to go1.22

- Dockerfile
Relate to: https://github.com/dymensionxyz/e2e-tests/actions/runs/8385594611/job/22964718176?pr=36
Close: #23
> CI: Build image with gcc enable

- .github/workflows/build_and_push_images.yml
----
Closes https://github.com/dymensionxyz/e2e-tests/issues/61
I have...
SDK Checklist
----;
For Reviewer:
---;
> CI: Images support linux/arm64 platform

- .github/workflows/build_and_push_images.yml
Reverts dymensionxyz/rollapp-wasm#28
>  "Revert "CI: Images support linux/arm64 platform ""

- README.md
- app/app.go
- go.mod
- go.sum
- rollappd/cmd/start.go
This pr: 
- Update ibc-go to v6.3.0
- Change some max bytes variable to flags when start
- Add hub genesis module
> feat: add hub genesis 

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> build(deps): update rdk to v1.5.0-beta

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> build(deps): update dymint to eb08e30da2c

- app/app.go
…fig.
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(app): Fixed bech32 on account keeper to not be hardcoded 

- CHANGELOG.md
- app/app.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix: updated IBC Keeper to use the sequencer keeper.

- README.md
- app/app.go
- go.mod
- go.sum
- rollappd/cmd/genaccounts.go
- rollappd/cmd/root.go
- rollappd/cmd/start.go
Reverts dymensionxyz/rollapp-wasm#59
> Revert "feat!: configure bech32prefix in genesis"

- .github/workflows/codeql.yml
- Dockerfile
- Makefile
- README.md
- app/app.go
- scripts/ibc/setup_ibc.sh
----
Closes #65 
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat: set bech32 prefix without changing source code

- .github/workflows/e2e-tests.yml
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore(tests): Wrong workflow name

- scripts/init.sh
- scripts/wasm/deploy_contract.sh
> Add bank metadata in genesis

- README.md
> docs: Update relayer version in README

- go.mod
- go.sum
- rollappd/cmd/genaccounts.go
- rollappd/cmd/root.go
> feat: add ethsecp256k1 as the default signing algo

- .github/workflows/e2e_test_upgrade.yml
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> tests(ci): add workflow for trigger upgrade hub e2e-test

- scripts/init.sh
> chores: change default block and envidence max bytes to 500000

- app/ante.go
- go.mod
- go.sum
https://github.com/dymensionxyz/e2e-tests/issues/258
----
Closes https://github.com/dymensionxyz/rollapp-wasm/issues/100
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(hub genesis); prevent opening new connections

- README.md
- scripts/init.sh
docs: update README to reflect the current init flow
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(scripts): fix init script to support mock backends

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> build(deps): bump dymint to `v1.2.0-rc01`

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> build(deps): bumped dymint to `v1.2.0-rc03`

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(deps): upstream fix - bump dymint `v1.2.0 rc03`

- scripts/settlement/register_sequencer_to_hub.sh
related to https://github.com/dymensionxyz/dymension/pull/1111
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore: update sequencer registration script to new arg sequence

- README.md
- app/app.go
- e2e/testing/chain.go
- go.mod
- go.sum
- scripts/init.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat(sequencers): wired sequencer rewards module.

- scripts/ibc/setup_ibc.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore: fix ibc setup script

- README.md
- scripts/ibc/setup_ibc.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore(scripts): use new relayer

- app/create_account_decorator.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> Removed ineffectual assignment

- go.mod
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(deps): bumped dymint to `d51b961e7` to fix stuck submission bug

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(deps): updated dymint and rdk by removing the replace

- .github/workflows/release_binary.yaml
- .goreleaser.yml
- Makefile
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> ci(binaries): add workflow and config to create mock binaries on release

- scripts/minimal_update_genesis_params.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore: add minimal updating stript for genesis

- .github/workflows/e2e-tests.yml
- .github/workflows/e2e_test_upgrade.yml
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore(ci): trigger workflow manually

- app/app.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix: removed MsgSend from allowed consensus msgs

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(deps): bumped dymint to v1.2.0-rc06 to fix compaction memory issue

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(version): bump dymint to c0e39f93d729

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(deps): fix tokenfactory init genesis validation 

- Makefile
- genesis-templates/DRS/1/genesis-mainnet.json
- genesis-templates/DRS/1/genesis-testnet.json
- scripts/generate-genesis-template.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat(makefile): create genesis template with DRS from make file

- go.mod
- go.sum
----
Closes #178 
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat(deps): validate-genesis-bridge command

- README.md
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> docs: bump relayer version

- genesis-templates/DRS/2/genesis-mainnet.json
- genesis-templates/DRS/2/genesis-testnet.json
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore(templates): add drs2 genesis templates

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(deps): update rdk to fix tokenfactory denom-metadata override

- .github/workflows/generate_genesis_template.yml
Close #175 
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore(ci): add CI to run generate-genesis-tempalte

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat(deps): bumped rdk to support tokenless feature

- Makefile
- genesis-templates/DRS/3/genesis-mainnet.json
- genesis-templates/DRS/3/genesis-testnet.json
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat(genesis-templates): add genesis templates for drs 3

- Dockerfile
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore: install curl for query in docker image

- app/app.go
- app/params/encoding.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(encoding): support eip712 encoding

- app/app.go
- app/params/encoding.go
(cherry picked from commit 8cd66ca427a9428c78857378ab19e70617f31d73)
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(encoding): support eip712 encoding 

- app/app.go
- app/upgrades/drs-4/constants.go
- app/upgrades/drs-4/upgrade.go
----
Closes #201 
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat(upgrade): add upgrade handler for DRS4

- app/app.go
- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(rollappparams): Validate gas price gov proposal param change

- Makefile
- genesis-templates/DRS/4/genesis-mainnet.json
- genesis-templates/DRS/4/genesis-testnet.json
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat(drs): updated makefile and templates to DRS 4

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat(deps): updated dymint to v1.3.0-rc02 to support skip validation height flag

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(deps): bump dymint to `v1.3.0-rc03` to fix multiple fork sync issue

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(deps): bumped rdk to v1.8.0-rc02 to include 2 minor fixes to tokenfactory and timeupgrade

- app/app.go
- app/upgrades/drs-4/upgrade.go
- app/upgrades/drs-5/constants.go
- app/upgrades/drs-5/upgrade.go
----
Closes #210 
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat(drs): added upgrade handler for drs 5

- Makefile
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat(makefile): added support for singing with ledger using cli

- Makefile
- genesis-templates/DRS/5/genesis-mainnet.json
- genesis-templates/DRS/5/genesis-testnet.json
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat(drs): generated genesis templates for DRS 5

- app/wasm.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(wasm): enable wasm proposals by default

- genesis-templates/DRS/5/genesis-mainnet.json
- genesis-templates/DRS/5/genesis-testnet.json
- scripts/generate-genesis-template.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat(genesis-templates): changed default delegator unbonding time in genesis template

- genesis-templates/DRS/5/genesis-mainnet.json
- genesis-templates/DRS/5/genesis-testnet.json
- scripts/generate-genesis-template.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat(genesis-template): changed delegator default min commision rate to be 0

- app/app.go
- app/upgrades/drs-6/constants.go
- app/upgrades/drs-6/upgrade.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat(upgrade): Add DRS 6 upgrade handler

- Makefile
- genesis-templates/DRS/6/genesis-mainnet.json
- genesis-templates/DRS/6/genesis-testnet.json
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat(drs): Add DRS 6 genesis templates

- app/app.go
- app/wasm.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(wasm): wire wasm proposals

- Makefile
- app/app.go
- app/upgrades/drs-7/constants.go
- app/upgrades/drs-7/upgrade.go
- genesis-templates/DRS/7/genesis-mainnet.json
- genesis-templates/DRS/7/genesis-testnet.json
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat(DRS): Added DRS 7 support

- .github/workflows/build_image_with_dymint.yml
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore(ci): Build RollApp with custom Dymint

- .github/workflows/build_image_with_dymint.yml
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore(ci): fix build image 

- .github/workflows/build_image_with_dymint.yml
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore(ci): checkout to rollapp-wasm repo before build image

- .github/workflows/build.yml
- .github/workflows/build_image_with_dymint.yml
- .github/workflows/e2e-tests.yml
- .github/workflows/e2e_test_upgrade.yml
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore(ci): bump actions/upload-artifact to v4

- go.mod
- go.sum
- rollappd/cmd/root.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> deps(rdk,dymint): update deps

- go.mod
- go.sum
- rollappd/cmd/root.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(deps): updated to rdk v1.8.1 to fix token factory change admin issue

- Makefile
- app/app.go
- app/upgrades/drs-8/constants.go
- app/upgrades/drs-8/upgrade.go
- genesis-templates/DRS/8/genesis-mainnet.json
- genesis-templates/DRS/8/genesis-testnet.json
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat(drs): add support for DRS 8

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore: bump wasmd version to v0.33.1-sdk0.46.2

- app/app.go
- app/upgrades/drs-2/upgrade.go
- app/upgrades/drs-3/upgrade.go
- app/upgrades/drs-4/upgrade.go
- app/upgrades/drs-5/upgrade.go
- app/upgrades/drs-6/upgrade.go
- app/upgrades/drs-7/upgrade.go
- app/upgrades/drs-8/upgrade.go
- app/upgrades/drs-9/constants.go
- app/upgrades/drs-9/doc.go
- app/upgrades/drs-9/upgrade.go
- app/upgrades/drs-9/upgrade_test.go
- app/upgrades/types.go
upgrade to version DRS 6, fix vesting accounts that have start and end times out of bounds due to having them expressed in milliseconds
----
Closes #233 
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(upgrade): correct vesting accounts start and end time

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(deps): revert rdk to v1.9

- app/app.go
- app/upgrades/drs-10/constants.go
- app/upgrades/drs-10/upgrade.go
- genesis-templates/DRS/10/genesis-mainnet.json
- genesis-templates/DRS/10/genesis-testnet.json
- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat(DRS): DRS 10
