dymensionxyz/rollapp-wasm

.github/pull_request_template.md, .github/workflows/codeql.yml, .github/workflows/golangci_lint.yml, .github/workflows/markdown_lint.yml, .markdownlint.yaml
=> workflows and template

Makefile, go.mod, go.sum, ra_wasm_be_rpc/backend/backend.go, ra_wasm_be_rpc/backend/rollapp_wasm_interceptor.go, ra_wasm_be_rpc/backend/sequencers.go, ra_wasm_be_rpc/namespaces/raw/api.go, ra_wasm_be_rpc/types/query_client.go, rollappd/cmd/root.go, rollappd/cmd/start.go
This PR integrate the Block Explorer Json-RPC server.
Later, once the Block Explorer service deployed, it can start connecting to the Json-RPC service on RollApp nodes for querying data.
New materials added:
- https://github.com/bcdevtools/block-explorer-rpc-cosmos is the skeleton for the Block Explorer Json-RPC service
- https://github.com/bcdevtools/wasm-block-explorer-rpc-cosmos is the extended version for Cosmwasm
=> feat(be): integrate block explorer Json-RPC server

go.mod, go.sum
This PR update version for 2 dependencies:
- [github.com/bcdevtools/block-explorer-rpc-cosmos v1.0.1 → v1.0.2](https://github.com/bcdevtools/block-explorer-rpc-cosmos/compare/v1.0.1...v1.0.2)
- [github.com/bcdevtools/wasm-block-explorer-rpc-cosmos v1.0.1 → v1.0.2](https://github.com/bcdevtools/wasm-block-explorer-rpc-cosmos/compare/v1.0.1...v1.0.2)
Content:
- Returns message signer.
- Limit number of input contracts for endpoint getting CW-20 balance.
=> chores(deps): bumps `block-explorer-rpc-cosmos v1.0.2` & `wasm-block-explorer-rpc-cosmos` v1.0.2

CHANGELOG.md, go.mod, go.sum, ra_wasm_be_rpc/backend/rollapp_wasm_interceptor.go, rollappd/cmd/start.go
This PR update version for 2 dependencies:
- [github.com/bcdevtools/block-explorer-rpc-cosmos v1.0.2 → v1.0.3](https://github.com/bcdevtools/block-explorer-rpc-cosmos/compare/v1.0.2...v1.0.3)
- [github.com/bcdevtools/wasm-block-explorer-rpc-cosmos v1.0.2 → v1.0.3](https://github.com/bcdevtools/wasm-block-explorer-rpc-cosmos/compare/v1.0.2...v1.0.3)
Content:
- Add new RPC endpoint `be_getLatestBlockNumber` for performance reason.
- `be_getAccount` returns contract code-id to determine if the given address is a contract.
- Correct name for an invalid named struct.
=> chores(deps): bumps `block-explorer-rpc-cosmos v1.0.3` & `wasm-block-explorer-rpc-cosmos v1.0.3`

CHANGELOG.md, go.mod, go.sum
This PR update version for 2 dependencies:
- [github.com/bcdevtools/block-explorer-rpc-cosmos v1.0.3 → v1.1.1](https://github.com/bcdevtools/block-explorer-rpc-cosmos/compare/v1.0.3...v1.1.1)
- [github.com/bcdevtools/wasm-block-explorer-rpc-cosmos v1.0.3 → v1.1.1](https://github.com/bcdevtools/wasm-block-explorer-rpc-cosmos/compare/v1.0.3...v1.1.1)
Content:
- Fix issue token contract balance of address not tracked.
- Response additional details of Wasm tx for indexer.
- Response additional field proto-type for account detection.
- Separate involvers extractor for wasm.
=> chores(deps): bumps `block-explorer-rpc-cosmos` and `wasm-block-explorer-rpc-cosmos` to v1.1.1

.github/workflows/changelog.yml, CHANGELOG.md
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
=> feat(ci): Add auto update changelog workflow

README.md, app/app.go, go.mod, go.sum, rollappd/cmd/genaccounts.go, rollappd/cmd/root.go, rollappd/cmd/start.go
----
Closes #56 
I have...
SDK Checklist
----;
For Reviewer:
---;
=> feat!: configure bech32prefix in genesis

app/app.go
----
Closes #58 
I have...
SDK Checklist
----;
For Reviewer:
---;
=> feat(app): Add modules authz and feegrant

CHANGELOG.md, go.mod, go.sum
This PR update version for 1 dependency:
- [github.com/bcdevtools/block-explorer-rpc-cosmos v1.1.2 → v1.2.3](https://github.com/bcdevtools/block-explorer-rpc-cosmos/compare/v1.1.2...v1.2.3)
Content:
- Add new API for performance and data consistency when querying via load-balancer.
- Improve content returns for indexer.
- Improve content returns by RPC.
- Fix some bugs.
- Fix RPC handler crash.
=> chores(deps): bumps `block-explorer-rpc-cosmos v1.2.3`

README.md, scripts/ibc/setup_ibc.sh
Close #89 
I have...
SDK Checklist
----;
For Reviewer:
---;
=> Chore(readme): update instruction and script for running rly v0.3.3-v2.5.2-relayer

app/ante.go, app/app.go, go.mod, go.sum
----
Closes #95 
I have...
SDK Checklist
----;
For Reviewer:
---;
=> feat(gasless): wire the `x/gasless` module

README.md, app/ante.go, app/bypass_ibc_fee_decorator.go, app/create_account_decorator.go, app/sigcheck_decorator.go, scripts/ibc/hub.json, scripts/ibc/setup_ibc.sh, scripts/settlement/register_rollapp_to_hub.sh, scripts/settlement/register_sequencer_to_hub.sh, x/callback/keeper/callback.go, x/cwerrors/keeper/subscriptions.go
Also update scripts a bit
----
Closes #126 
I have...
SDK Checklist
----;
For Reviewer:
---;
=> feat(ante): skip fees for IBC messages 

go.mod
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
=> fix(deps): bumped rdk to 3fe31b2db to fix denom-metadata transfer on unrelayed packets

README.md, go.mod, go.sum, scripts/init.sh, scripts/settlement/register_rollapp_to_hub.sh
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
=> fix: rollapp param in scripts/init.sh 

.github/workflows/golangci_lint.yml
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
=> chore: updated linter

app/apptesting/apptesting.go, go.mod, x/tokenfactory/bindings/message_plugin.go, x/tokenfactory/bindings/query_plugin.go, x/tokenfactory/bindings/types/msg.go, x/tokenfactory/types/denoms.go, x/tokenfactory/types/errors.go, x/tokenfactory/types/genesis.go, x/tokenfactory/types/msgs.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
=> fix: lint fix deprecated packages

app/app.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
=> feat(upgrade): add drs validation to allow gov based upgrades

app/app.go, go.mod, go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
=> feat(deps): new genesis-bridge flow and rollappparams upgrade fix

app/test_helpers.go, app/upgrades/drs-2/upgrade.go, e2e/testing/chain.go, go.mod, go.sum, x/cwerrors/keeper/sudo_errors_test.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
=> feat(deps): bump to last rdk version + tests fix

app/upgrades/drs-3/upgrade.go
It fails because there are params not defined. replaced getting all params to get the version. 
Closes #198 
I have...
SDK Checklist
----;
For Reviewer:
---;
=> fix(upgrade): drs upgrade from 1 to 3 fix 
